version: "3"

services:
  theming-service:
    image: smartspike/theming-service
    ports:
      - "9000:9000"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/themingdb?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init.sql